import streamlit as st
import io
import time
from datetime import date
import feedparser
from bs4 import BeautifulSoup
import pandas as pd
import pandas as pd
import anthropic
import markdown
from xhtml2pdf import pisa

import config

# --- UI CONFIGURATION (LIGHT MODE DEFAULT) ---
st.set_page_config(
    page_title="VinDynamic AI Agent",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- CORE LOGIC ---
BATCH_SIZE = 5

def generate_pdf(md_text):
    """
    Đúc chuỗi Markdown sang File PDF Nhị Phân (Binary) bằng HTML Proxy
    """
    html_content = markdown.markdown(md_text, extensions=['tables'])
    
    # CSS Trắng đen, Tiêu chuẩn Báo cáo Quản trị Doanh nghiệp
    pdf_html = f"""
    <html>
    <head>
    <style>
        @page {{ margin: 2cm; }}
        body {{ font-family: Helvetica, Arial, sans-serif; font-size: 11pt; line-height: 1.6; color: #333; }}
        h1, h2, h3 {{ color: #004d99; }}
        h2 {{ border-bottom: 2px solid #eee; padding-bottom: 5px; padding-top: 15px;}}
        ul {{ margin-bottom: 15px; }}
        li {{ margin-bottom: 8px; }}
        a {{ color: #0066cc; text-decoration: none; }}
        hr {{ border: 0; border-top: 1px solid #ccc; }}
    </style>
    </head>
    <body>
    <h1 style="text-align: center; color: #333;">VINDYNAMIC MARKET INTELLIGENCE</h1>
    <hr>
    {html_content}
    <br><br>
    <p style="text-align: right; color: #666; font-size: 9pt;"><i>Generated by VinDynamic AI Core pipeline</i></p>
    </body>
    </html>
    """
    
    result_file = io.BytesIO()
    pisa_status = pisa.CreatePDF(
        io.BytesIO(pdf_html.encode('utf-8')),
        dest=result_file,
        encoding='utf-8'
    )
    
    if pisa_status.err:
        return None
    return result_file.getvalue()

def clean_html(html_content):
    if not html_content:
        return ""
    try:
        soup = BeautifulSoup(html_content, "html.parser")
        return soup.get_text(separator=" ", strip=True)
    except:
        return ""

def filter_by_keywords(text, keyword_list):
    if not text:
        return False
    text = text.lower()
    for keyword in keyword_list:
        if keyword.strip().lower() in text:
            return True
    return False

def fetch_rss_feeds(rss_urls, keyword_list, progress_callback=None):
    all_articles = []
    total_urls = len(rss_urls)
    
    for i, url in enumerate(rss_urls):
        url = url.strip()
        if not url: continue
        
        if progress_callback:
            progress_callback(i / total_urls, f"Fetching data from: {url} ...")
            
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries:
                title = entry.get("title", "")
                summary_raw = entry.get("summary", "")
                summary_clean = clean_html(summary_raw)
                
                # Pre-filtering
                if filter_by_keywords(title, keyword_list) or filter_by_keywords(summary_clean, keyword_list):
                    all_articles.append({
                        "title": title,
                        "link": entry.link,
                        "published": entry.get("published", ""),
                        "summary": summary_clean,
                        "feed_source": url
                    })
        except Exception as e:
            st.error(f"Error fetching feed {url}: {e}")
            
    # Deduplicate
    unique_links = set()
    deduped_articles = []
    for article in all_articles:
        if article["link"] not in unique_links:
            unique_links.add(article["link"])
            deduped_articles.append(article)
            
    if progress_callback:
        progress_callback(1.0, "Data collection complete!")
        
    return deduped_articles

def synthesize_batch(api_key, batch_index, batch_data, persona, report_format, use_memory=False, past_briefings=[]):
    """
    Data Serialization and Direct Communication with Claude AI.
    """
    today_str = date.today().strftime("%B %d, %Y")
    
    # 1. Serialization of raw data
    raw_content = ""
    for idx, art in enumerate(batch_data):
        raw_content += f"[{idx+1}] TITLE: {art['title']}\n"
        raw_content += f"URL: {art['link']}\n"
        raw_content += f"SUMMARY: {art['summary'][:1500]}...\n"
        raw_content += "-" * 40 + "\n"
        
    # 2. Process Memory Context
    memory_block = ""
    if use_memory and past_briefings:
        memory_block = (
            "CONTEXT FROM PREVIOUS BRIEFINGS (last 5 days):\n"
            + "\n\n---\n\n".join(past_briefings[-5:])
            + "\n\nFlag any ESCALATING TRENDS or RECURRING THEMES "
              "you notice compared to previous days.\n\n"
        )
        
    # 3. Final Prompt Structure (User Prompt + Input Data)
    prompt_content = f"{memory_block}Today is {today_str}. Here are today's matched articles:\n\n{raw_content}\n\n{report_format}"

    # --- API CONNECTION (MOCK OR REAL) ---
    if not api_key:
        time.sleep(2) # Simulate Anthropic delay
        
        mock_output_md = f"""## Market trends
* (Mock) The industrial automation sector continues to rise with new AMR deployments.
* Factories in Europe and China are doubling their budget for flexible robotic arms.

## Competitor & industry moves
* (Mock Data) Universal Robots announced a new generation of cobots with 4D micro-force sensors.
* KUKA strengthens European supply chains by acquiring X-Sensors.

## Funding & M&A
* 🇺🇸 Softbank poured $500M USD into Boston Dynamics' domestic Humanoid project.

## Southeast Asia & Vietnam spotlight
* 🇻🇳 Vinamilk and Samsung Bắc Ninh open a mega Logistics plant utilizing robotic arms.
* 🇸🇬 The Singaporean Government established a 100M SGD fund for Deep-Tech Automation startups.

## Strategic implications for VinDynamic
* **Opportunity 1:** Electronics giants (Samsung) in VN are desperate for automated chip-handling solutions. VinDynamic should propose a Pilot package integrating soft grippers to secure a 100K$ contract.
* **Threat:** Manufacturers from Guangdong (CN) are entering the SEA market, slashing AGV prices by 15%.
* **Action:** Shift positioning. Reduce hardware competition, focus heavily on AI Controllers (Navigational Intelligence).

## Top 3 articles to read in full
1. [Robotics News 1]({batch_data[0]['link']}) - {batch_data[0]['title']}
2. [(Mock Data Hidden) Pending remaining titles](#) - ...

***Headline of the day***: A pivotal day for the market as multi-million dollar investments pour heavily into the Humanoid ecosystem, opening a bright door for VinDynamic to exploit the soft-gripper logistics chain.
"""
        return {
            "batch_index": batch_index,
            "articles_processed": len(batch_data),
            "report_content": mock_output_md
        }
    else:
        # REAL API CALL TO ANTHROPIC SDK
        try:
            client = anthropic.Anthropic(api_key=api_key)
            message = client.messages.create(
                model=st.session_state.get("selected_model", "claude-sonnet-4-6"),
                max_tokens=2500,
                system=persona,
                messages=[{"role": "user", "content": prompt_content}]
            )
            return {
                "batch_index": batch_index,
                "articles_processed": len(batch_data),
                "report_content": message.content[0].text
            }
        except Exception as e:
            return {
                "batch_index": batch_index,
                "articles_processed": len(batch_data),
                "report_content": f"🚨 **SYSTEM ERROR CALLING CLAUDE API:** {str(e)}\n\nPlease double-check your API Key and billing status."
            }

# --- UI BUILDING ---

def main():
    # --- HEADER & SETTINGS (TOP RIGHT) ---
    colTitle, colSettings = st.columns([8, 2])
    
    with colTitle:
        st.title("🤖 VinDynamic Intelligence Agent")
        st.markdown("Specialized AI Architecture for Market Intelligence. 🧠 Featuring **Context Memory** & **Strict Report Formatting**.")
        
    with colSettings:
        st.write("") # Vertical alignment
        st.write("") 
        with st.popover("⚙️ Settings (Keys)", use_container_width=True):
            st.markdown("**Platform Credentials**")
            default_key = config.ANTHROPIC_API_KEY if config.ANTHROPIC_API_KEY else ""
            api_key = st.text_input("🔑 Anthropic API Key", type="password", help="Được bảo mật cục bộ ở file .env dưới máy.", value=default_key)
            if st.button("💾 Lưu vĩnh viễn Key (lần sau tự nhận)", use_container_width=True):
                if api_key:
                    import os
                    from dotenv import set_key
                    if not os.path.exists(".env"):
                        open(".env", "w").close()
                    set_key(".env", "ANTHROPIC_API_KEY", api_key)
                    # Giữ chốt Key vào RAM hiện tại mà không cần Restart nóng
                    config.ANTHROPIC_API_KEY = api_key
                    st.success("✅ Đã đóng băng Key vào ổ cứng hệ thống (.env) an toàn 100%!")
                else:
                    st.warning("Xin hãy dán API Key trước khi bấm Lưu.")
            
            st.divider()
            st.markdown("**Core Parameters**")
            # Cập nhật danh sách model thực tế từ API trả về của User Org
            available_models = [
                "claude-sonnet-4-6", 
                "claude-opus-4-6", 
                "claude-sonnet-4-5-20250929", 
                "claude-haiku-4-5-20251001"
            ]
            selected_model = st.selectbox("🧠 AI Model", available_models, key="selected_model")
            max_articles = st.number_input("Max Articles to Process", min_value=10, max_value=500, value=50, step=10, help="Giới hạn số lượng bài để tiết kiệm Token", key="max_articles_limit")

    # 1. SIDEBAR: Configuration inputs
    with st.sidebar:
        st.header("⚙️ Agent Configuration")
        
        if not api_key:
            st.info("💡 Running in MOCK mode. Add your Anthropic API Key in the top-right Settings to enable Claude.")

        st.subheader("🧠 Memory Hooks")
        use_memory = st.toggle("Inject Past 5 Days Context?", value=True)
        if use_memory:
            st.caption("🔍 Claude will cross-reference past reports to detect escalating competitor trends.")

        st.subheader("📰 RSS Sources (Daily Scan)")
        default_rss = "\n".join(config.RSS_FEEDS)
        rss_input = st.text_area("Source List (1 URL per line)", value=default_rss, height=180)
        rss_urls = [url.strip() for url in rss_input.split('\n') if url.strip()]
        
        st.subheader("🎯 Pre-Filtering Keywords")
        default_kw = ", ".join(config.KEYWORDS)
        kw_input = st.text_area("Comma-separated values", value=default_kw, height=100)
        keyword_list = [kw.strip() for kw in kw_input.split(',') if kw.strip()]
        
        st.subheader("🕵️ Persona Injection")
        persona_input = st.text_area("System Directive", value=config.ANALYST_PERSONA, height=200)

        st.subheader("📑 Report Architecture")
        try:
            default_format = config.REPORT_FORMAT
        except:
            default_format = "Placeholder Format. Please refresh."
        format_input = st.text_area("Strict Output Format (Markdown)", value=default_format, height=250)

    # 2. MAIN AREA: Execution
    st.divider()
    
    col1, col2 = st.columns([1, 4])
    with col1:
        start_btn = st.button("🚀 Run System Pipeline", type="primary", use_container_width=True)
        
    if start_btn:
        st.info("Loading Agent Pipeline...")
        
        progress_bar = st.progress(0.0)
        status_text = st.empty()
        
        def update_progress(ratio, text):
            progress_bar.progress(ratio)
            status_text.text(text)
        
        st.subheader("Tier 1 & 2: Data Pipeline (Web Fetching & Prefiltering)")
        with st.spinner("Parsing RSS feeds & matching keywords via BeautifulSoup..."):
            articles_raw = fetch_rss_feeds(rss_urls, keyword_list, progress_callback=update_progress)
            
            # Use the user-defined limit instead of hardcoding 10
            limit = st.session_state.get("max_articles_limit", 50)
            articles = articles_raw[:limit]
        
        st.success(f"Parsing complete! Successfully captured **{len(articles_raw)}** articles related to SEA Robotics. Filtering down to the top {len(articles)} for AI processing.")
        
        # Display Dataframe
        if len(articles) > 0:
            df = pd.DataFrame(articles)[['title', 'feed_source', 'link']]
            st.dataframe(df, use_container_width=True, hide_index=True)
            
            # AI Inference Stage
            st.subheader("Tier 3: Core Intelligence (Claude Synthesis)")
            
            aggregated_reports = []
            total_articles = len(articles)
            
            # Simulated previous memory since we don't have a DB hooked up yet
            past_mock_briefings = [
                 "[Pre-DB Memory] 2 days ago (Mar 29): Notable deployment of AI Vision Cameras in VN garment factories.",
                 "[Pre-DB Memory] Yesterday (Mar 30): Logistics M&A is heating up with the Alpha acquisition."
            ]
            
            with st.status("Aggregating Context & Data -> Requesting comprehensive report from Claude...", expanded=True) as status:
                st.write(f"Serializing all {total_articles} Articles -> Injecting Context & Format -> Dispatching Payload...")
                
                result = synthesize_batch(
                    api_key=api_key, 
                    batch_index=1, 
                    batch_data=articles, 
                    persona=persona_input, 
                    report_format=format_input, 
                    use_memory=use_memory, 
                    past_briefings=past_mock_briefings
                )
                
                status.update(label="Claude completed the Daily Intelligence Briefing! ✅", state="complete", expanded=False)
            
            # Final Output Presentation
            st.subheader("📊 Tier 4: Final Intelligence Briefing (Markdown)")
            
            st.markdown(f"#### 📂 Mega-Report Synthesized from {result['articles_processed']} matching articles:")
            st.markdown(result['report_content'])
            
            st.divider()
            st.subheader("📥 Export Intelligence Report")
            
            # Khởi tạo quá trình vẽ file PDF
            with st.spinner("Đang hóa hơi Markdown để ép mặt chữ dập File PDF..."):
                pdf_bytes = generate_pdf(result['report_content'])
                
            if pdf_bytes:
                st.download_button(
                    label="📄 Download Report as PDF",
                    data=pdf_bytes,
                    file_name=f"VinDynamic_Intelligence_Report_{date.today().strftime('%Y-%m-%d')}.pdf",
                    mime="application/pdf",
                    type="primary"
                )
                st.balloons()
            else:
                st.error("🚨 PDF Generation Failed. The system could not compile the physical file.")
        else:
            st.warning("No relevant articles passed the keyword filter today. Consider relaxing your constraints!")

if __name__ == "__main__":
    main()
