import streamlit as st
import io
import time
import json
import os
import re
from datetime import date, datetime
import feedparser
from bs4 import BeautifulSoup
import pandas as pd
import anthropic
import markdown
from xhtml2pdf import pisa

import config

# --- UI CONFIGURATION (LIGHT MODE DEFAULT) ---
st.set_page_config(
    page_title="VinDynamic AI Agent v2",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- CORE LOGIC ---
HISTORY_FILE = "history.json"
KB_FILE = "knowledge_base.md"

def load_history():
    if os.path.exists(HISTORY_FILE):
        try:
            with open(HISTORY_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return {"links": []}
    return {"links": []}

def save_history(links_to_add):
    hist = load_history()
    hist["links"].extend(links_to_add)
    # Deduplicate links
    hist["links"] = list(set(hist["links"]))
    # Keep only the last 2000 links
    if len(hist["links"]) > 2000:
        hist["links"] = hist["links"][-2000:]
    
    with open(HISTORY_FILE, "w", encoding="utf-8") as f:
        json.dump(hist, f, ensure_ascii=False, indent=2)

def load_kb():
    if os.path.exists(KB_FILE):
        with open(KB_FILE, "r", encoding="utf-8") as f:
            return f.read()
    return "The Knowledge Base is empty."

def save_kb(content):
    with open(KB_FILE, "w", encoding="utf-8") as f:
        f.write(content)

def generate_pdf(md_text):
    """
    Đúc chuỗi Markdown sang File PDF
    """
    md_text = md_text.replace("‘", "'").replace("’", "'").replace("“", '"').replace("”", '"').replace("–", "-").replace("—", "-")
    
    html_content = markdown.markdown(md_text, extensions=['tables'])
    
    pdf_html = f"""
    <html>
    <head>
    <meta charset="UTF-8">
    <style>
        @page {{ margin: 2cm; }}
        body {{ font-family: Helvetica, Arial, sans-serif; font-size: 11pt; line-height: 1.6; color: #333; }}
        h1, h2, h3 {{ color: #004d99; }}
        h2 {{ border-bottom: 2px solid #eee; padding-bottom: 5px; padding-top: 15px;}}
        ul {{ margin-bottom: 15px; }}
        li {{ margin-bottom: 8px; }}
        a {{ color: #0066cc; text-decoration: none; }}
        hr {{ border: 0; border-top: 1px solid #ccc; }}
        em {{ color: #666; font-size: 10pt; }}
    </style>
    </head>
    <body>
    <h1 style="text-align: center; color: #333;">VINDYNAMIC MARKET INTELLIGENCE</h1>
    <p style="text-align: center;">Report Date: {date.today().strftime('%Y-%m-%d')}</p>
    <hr>
    {html_content}
    <br><br>
    <p style="text-align: right; color: #666; font-size: 9pt;"><i>Generated by VinDynamic 3-Stage AI Agent</i></p>
    </body>
    </html>
    """
    
    result_file = io.BytesIO()
    pisa_status = pisa.CreatePDF(
        io.BytesIO(pdf_html.encode('utf-8')),
        dest=result_file,
        encoding='utf-8'
    )
    if pisa_status.err:
        return None
    return result_file.getvalue()

def clean_html(html_content):
    if not html_content:
        return ""
    try:
        # Optimization: Clear white spaces aggressively, strip extra HTML
        soup = BeautifulSoup(html_content, "html.parser")
        text = soup.get_text(separator=" ", strip=True)
        text = re.sub(r'\s+', ' ', text)
        return text[:1000] # Truncate to lower token usage
    except:
        return ""

def filter_by_keywords(text, keyword_list):
    if not text:
        return False, None
    text = text.lower()
    
    locale_keywords = ['vietnam', 'việt nam', 'southeast asia', 'asean', 'singapore', 'thailand', 'malaysia', 'indonesia', 'philippines', 'asia']
    
    matched = False
    is_locale = False
    
    for keyword in keyword_list:
        clean_kw = keyword.strip().lower()
        if clean_kw in text:
            matched = True
            if clean_kw in locale_keywords:
                is_locale = True
                
    if matched:
        category = "Locale / Regional News" if is_locale else "Global Tech & Market"
        return True, category
        
    return False, None

def fetch_rss_feeds(rss_urls, keyword_list, progress_callback=None, previous_links=set()):
    all_articles = []
    total_urls = len(rss_urls)
    
    for idx, url in enumerate(rss_urls):
        url = url.strip()
        if not url: continue
        
        if progress_callback:
            progress_callback((idx + 1) / total_urls, f"Đang quét nguồn: {url} ...")
            
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries:
                link = entry.get("link", "")
                if link and (link in previous_links):
                    continue
                
                title = entry.get("title", "")
                summary_raw = entry.get("summary", "")
                summary_clean = clean_html(summary_raw)
                published_raw = entry.get("published", entry.get("pubDate", "Recent"))
                
                # Dynamic Categorization based on keywords
                matched_title, cat_title = filter_by_keywords(title, keyword_list)
                matched_sum, cat_sum = filter_by_keywords(summary_clean, keyword_list)
                
                if matched_title or matched_sum:
                    final_category = "Locale / Regional News" if (cat_title == "Locale / Regional News" or cat_sum == "Locale / Regional News") else "Global Tech & Market"
                    
                    domain = url.split("//")[-1].split("/")[0].replace("www.", "")
                    all_articles.append({
                        "category": final_category,
                        "title": title,
                        "link": link,
                        "summary": summary_clean,
                        "source_domain": domain,
                        "published": published_raw
                    })
        except Exception as e:
            st.error(f"Lỗi nguồn {url}: {e}")
            
    # Deduplicate automatically
    unique_links = set()
    deduped_articles = []
    for article in all_articles:
        if article["link"] not in unique_links:
            unique_links.add(article["link"])
            deduped_articles.append(article)
            
    if progress_callback:
        progress_callback(1.0, "Thu thập hoàn tất! Đã tự động phân mảng dữ liệu Local/Global dựa trên Keyword.")
        
    return deduped_articles

def run_anthropic_stage(api_key, model_choice, system_prompt, user_content):
    if not api_key:
        time.sleep(2)
        return f"MOCK RESULT for Stage -> {user_content[:100]}..."
    try:
        client = anthropic.Anthropic(api_key=api_key)
        message = client.messages.create(
            model=model_choice,
            max_tokens=4000,
            system=system_prompt,
            messages=[{"role": "user", "content": user_content}]
        )
        return message.content[0].text
    except Exception as e:
        st.error(f"API Error ({model_choice}): {e}")
        return None

# --- UI BUILDING ---

def main():
    colTitle, colSettings = st.columns([8, 2])
    
    with colTitle:
        st.title("🤖 VinDynamic Agent V2 (Continuous Intelligence)")
        st.markdown("Kiến trúc **3-Stage Pipeline** (Tổng hợp thô -> Cập nhật Knowledge Base -> Xuất Báo cáo chuẩn Harvard) để tối ưu Token và bảo toàn thông tin mọi mảng.")
        
    with colSettings:
        st.write("") 
        st.write("") 
        with st.popover("⚙️ Settings (Keys)", use_container_width=True):
            st.markdown("**Platform Credentials**")
            default_key = config.ANTHROPIC_API_KEY if config.ANTHROPIC_API_KEY else ""
            api_key = st.text_input("🔑 Anthropic API Key", type="password", value=default_key)
            if st.button("💾 Lưu vĩnh viễn Key (lần sau tự nhận)", use_container_width=True):
                if api_key:
                    from dotenv import set_key
                    if not os.path.exists(".env"):
                        open(".env", "w").close()
                    set_key(".env", "ANTHROPIC_API_KEY", api_key)
                    config.ANTHROPIC_API_KEY = api_key
                    st.success("✅ Đã đóng băng Key vào ổ cứng an toàn 100%!")
                else:
                    st.warning("Xin hãy dán API Key trước khi bấm Lưu.")
            
            st.divider()
            st.markdown("**Model Routing Policy**")
            st.info("Hệ thống tự động dùng **Haiku** (rẻ nhất) cho Stage 1 & 2. Chỉ Stage 3 mới dùng model bên dưới.")
            available_models = [
                "claude-sonnet-4-6", 
                "claude-sonnet-3-5-20241022",
                "claude-opus-4-6", 
            ]
            selected_report_model = st.selectbox("🧠 Stage 3 Model (Analyst Model)", available_models, key="selected_model")
            
            # Cấu hình "rẻ" cho Model Stage 1 & 2 dựa trên prompt user.
            haiku_model = "claude-haiku-4-5-20251001" 

    # 1. SIDEBAR: Configuration inputs
    with st.sidebar:
        st.header("⚙️ Agent Configuration")
        
        if not api_key:
            st.info("💡 Running in MOCK mode. Add your Anthropic API Key in Settings.")

        st.subheader("📰 RSS Sources (Daily Scan)")
        default_rss = "\n".join(config.RSS_FEEDS) if hasattr(config, 'RSS_FEEDS') else ""
        rss_input = st.text_area("Source List (1 URL per line)", value=default_rss, height=180)
        rss_urls = [url.strip() for url in rss_input.split('\n') if url.strip()]
        
        st.subheader("🎯 Pre-Filtering Keywords")
        default_kw = ", ".join(config.KEYWORDS)
        kw_input = st.text_area("Từ khóa lọc nội dung", value=default_kw, height=100)
        keyword_list = [kw.strip() for kw in kw_input.split(',') if kw.strip()]
        
        if st.button("🗑️ Reset Knowledge Base & Links"):
            if os.path.exists(HISTORY_FILE):
                os.remove(HISTORY_FILE)
            if os.path.exists(KB_FILE):
                os.remove(KB_FILE)
            st.success("Đã xóa trắng Trí não hệ thống!")
            st.rerun()

    # 2. MAIN AREA: Execution
    st.divider()
    
    col1, col2 = st.columns([1, 4])
    with col1:
        start_btn = st.button("🚀 Kích hoạt Agent V2", type="primary", use_container_width=True)
        
    # --- KHỐI THỰC THI CHÍNH ---
    if start_btn:
        progress_bar = st.progress(0.0)
        status_text = st.empty()
        
        def update_progress(ratio, text):
            progress_bar.progress(ratio)
            status_text.text(text)
            
        history_links = load_history().get("links", [])
        
        # [DATA FETCHING]
        with st.spinner("Đang gom dữ liệu từ RSS và phân mảng Auto/Locale/Global..."):
            articles_raw = fetch_rss_feeds(rss_urls, keyword_list, progress_callback=update_progress, previous_links=set(history_links))
            st.session_state['pipeline_df'] = pd.DataFrame(articles_raw)
            
        if len(articles_raw) > 0:
            st.session_state['pipeline_success'] = True
            
            # Text serialization for Stage 1
            raw_text_payload = ""
            for idx, a in enumerate(articles_raw):
                raw_text_payload += f"[{idx+1}] CATEGORY: {a['category']}\n"
                raw_text_payload += f"SOURCE_NAME: {a['source_domain']}\n"
                raw_text_payload += f"DATE: {a.get('published', 'Recent')}\n"
                raw_text_payload += f"URL: {a['link']}\n"
                raw_text_payload += f"TITLE: {a['title']}\nSUMMARY: {a['summary']}\n---\n"
                
            # [STAGE 1: HAIPU SUMMARIZER]
            st.subheader("⚙️ Stage 1: Thematic Summarization")
            with st.spinner(f"Đang ra lệnh cho {haiku_model} gom nhóm mảng thông tin cho {len(articles_raw)} bài báo..."):
                stage1_prompt = config.SUMMARIZE_PROMPT.format(batch_size=len(articles_raw))
                thematic_summary = run_anthropic_stage(api_key, haiku_model, stage1_prompt, raw_text_payload)
            st.markdown("✅ *Stage 1 Hoàn tất. Đã băm nhỏ và rút ý.*")
            
            # [STAGE 2: KNOWLEDGE BASE MERGING]
            st.subheader("⚙️ Stage 2: Cập nhật Knowledge Base Vĩnh viễn")
            with st.spinner(f"Đang nén và dung hợp chi tiết mới vào Knowledge Base cũ... (Model: {haiku_model})"):
                old_kb = load_kb()
                stage2_prompt = config.MERGE_KB_PROMPT.format(old_kb=old_kb, new_summaries=thematic_summary)
                updated_kb_content = run_anthropic_stage(api_key, haiku_model, stage2_prompt, f"Current Date Context: {date.today().strftime('%Y-%m-%d')}")
                
                if updated_kb_content:
                    save_kb(updated_kb_content)  # Lưu file
                    st.session_state['kb_content'] = updated_kb_content
            st.markdown("✅ *Stage 2 Hoàn tất. Knowledge Base đã được lưu trữ.*")
            
            # [STAGE 3: HIGHER-ORDER ANALYSIS REPORT]
            st.subheader("⚙️ Stage 3: Nhả Báo Cáo Phân Tích Chuẩn Harvard")
            with st.spinner(f"Đang khởi động {selected_report_model} (High-IQ Model) viết báo cáo từ Bộ Não đã nén..."):
                final_kb = load_kb()
                stage3_prompt = config.ANALYST_REPORT_PROMPT
                final_report_md = run_anthropic_stage(api_key, selected_report_model, stage3_prompt, f"Làm báo cáo Dựa trên Kho Kiến thức này:\n\n{final_kb}")
                
                if final_report_md:
                    st.session_state['report_content'] = final_report_md
                    pdf_bytes = generate_pdf(final_report_md)
                    st.session_state['pdf_bytes'] = pdf_bytes
            
            st.markdown("✅ *Stage 3 Hoàn tất! Báo cáo chiến lược đã sẵn sàng!*")
            
            # Update History DB so next runs won't fetch redundant items
            new_links = [art['link'] for art in articles_raw]
            save_history(new_links)
            
        else:
            st.session_state['pipeline_success'] = True
            st.session_state['pipeline_df'] = pd.DataFrame()
            st.session_state['report_content'] = "⚠️ **Không có tin tức nào mới (Delta = 0)**. Mọi thứ đã có trong Knowledge Base."
            st.session_state['pdf_bytes'] = None
            st.session_state['kb_content'] = load_kb()

    # --- TABS HIỂN THỊ GIAO DIỆN (LƯU PERSISTENT) ---
    st.divider()
    tab1, tab2, tab3 = st.tabs(["🧠 Trí Não Tri Thức (Knowledge Base) ", "📊 Báo Cáo Phân Tích (Final Report) ", "📂 Dữ Liệu Raw Hút Về"])
    
    with tab1:
        st.info("Bản nén lưu trữ dung lượng nhẹ trên máy để LLM nhớ lâu đài không tốn tiền API. Mới nhất được đẩy lên đầu tiên (Sắp xếp thời gian).")
        st.markdown(st.session_state.get('kb_content', load_kb()))
        
    with tab2:
        if st.session_state.get('report_content'):
            st.markdown(st.session_state.get('report_content'))
            st.divider()
            if st.session_state.get('pdf_bytes'):
                st.download_button(
                    label="📄 Tải Báo Cáo (PDF Format)",
                    data=st.session_state['pdf_bytes'],
                    file_name=f"VinDynamic_Strategy_{date.today().strftime('%Y-%m-%d')}.pdf",
                    mime="application/pdf",
                    type="primary"
                )
        else:
            st.write("Chưa có báo cáo nào được tạo ấn bản trong phiên dùng này. Hãy chạy Pipeline để sinh Báo cáo mới.")
            
    with tab3:
        if st.session_state.get('pipeline_success') and st.session_state.get('pipeline_df') is not None and not st.session_state['pipeline_df'].empty:
            st.success(f"Quét được {len(st.session_state['pipeline_df'])} tin bài mới thuộc nhiều mảng khác nhau.")
            st.dataframe(st.session_state['pipeline_df'], use_container_width=True, hide_index=True)
        else:
            st.write("Chưa scan được bài báo mới.")

if __name__ == "__main__":
    main()
