import streamlit as st
import io
import time
import json
import os
from datetime import date
import feedparser
from bs4 import BeautifulSoup
import pandas as pd
import anthropic
import markdown
from xhtml2pdf import pisa

import config

# --- UI CONFIGURATION (LIGHT MODE DEFAULT) ---
st.set_page_config(
    page_title="VinDynamic AI Agent",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- CORE LOGIC ---
BATCH_SIZE = 5
HISTORY_FILE = "history.json"

def load_history():
    if os.path.exists(HISTORY_FILE):
        try:
            with open(HISTORY_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return {"links": [], "last_report": ""}
    return {"links": [], "last_report": ""}

def save_history(links_to_add, report_text):
    hist = load_history()
    hist["links"].extend(links_to_add)
    # Deduplicate links to prevent massive file growth
    hist["links"] = list(set(hist["links"]))
    # Keep only the last 2000 links
    if len(hist["links"]) > 2000:
        hist["links"] = hist["links"][-2000:]
    hist["last_report"] = report_text
    
    with open(HISTORY_FILE, "w", encoding="utf-8") as f:
        json.dump(hist, f, ensure_ascii=False, indent=2)

def generate_pdf(md_text):
    """
    Đúc chuỗi Markdown sang File PDF Nhị Phân (Binary) bằng HTML Proxy
    """
    # Fix unicode issues before generating PDF (smart quotes, dashes turning into box/mojibake)
    md_text = md_text.replace("‘", "'").replace("’", "'").replace("“", '"').replace("”", '"').replace("–", "-").replace("—", "-")
    
    html_content = markdown.markdown(md_text, extensions=['tables'])
    
    # CSS Trắng đen, Tiêu chuẩn Báo cáo Quản trị Doanh nghiệp
    pdf_html = f"""
    <html>
    <head>
    <meta charset="UTF-8">
    <style>
        @page {{ margin: 2cm; }}
        body {{ font-family: Helvetica, Arial, sans-serif; font-size: 11pt; line-height: 1.6; color: #333; }}
        h1, h2, h3 {{ color: #004d99; }}
        h2 {{ border-bottom: 2px solid #eee; padding-bottom: 5px; padding-top: 15px;}}
        ul {{ margin-bottom: 15px; }}
        li {{ margin-bottom: 8px; }}
        a {{ color: #0066cc; text-decoration: none; }}
        hr {{ border: 0; border-top: 1px solid #ccc; }}
    </style>
    </head>
    <body>
    <h1 style="text-align: center; color: #333;">VINDYNAMIC MARKET INTELLIGENCE</h1>
    <hr>
    {html_content}
    <br><br>
    <p style="text-align: right; color: #666; font-size: 9pt;"><i>Generated by VinDynamic AI Core pipeline</i></p>
    </body>
    </html>
    """
    
    result_file = io.BytesIO()
    pisa_status = pisa.CreatePDF(
        io.BytesIO(pdf_html.encode('utf-8')),
        dest=result_file,
        encoding='utf-8'
    )
    
    if pisa_status.err:
        return None
    return result_file.getvalue()

def clean_html(html_content):
    if not html_content:
        return ""
    try:
        soup = BeautifulSoup(html_content, "html.parser")
        return soup.get_text(separator=" ", strip=True)
    except:
        return ""

def filter_by_keywords(text, keyword_list):
    if not text:
        return False
    text = text.lower()
    for keyword in keyword_list:
        if keyword.strip().lower() in text:
            return True
    return False

def fetch_rss_feeds(rss_urls, keyword_list, progress_callback=None, previous_links=set()):
    all_articles = []
    total_urls = len(rss_urls)
    
    for i, url in enumerate(rss_urls):
        url = url.strip()
        if not url: continue
        
        if progress_callback:
            progress_callback(i / total_urls, f"Fetching data from: {url} ...")
            
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries:
                link = entry.get("link", "")
                
                # OPTIMIZE TOKENS: Bỏ qua bài đã có trong History (chỉ duyệt bài mới nhất / Delta)
                if link and (link in previous_links):
                    continue
                
                title = entry.get("title", "")
                summary_raw = entry.get("summary", "")
                summary_clean = clean_html(summary_raw)
                
                # Pre-filtering
                if filter_by_keywords(title, keyword_list) or filter_by_keywords(summary_clean, keyword_list):
                    all_articles.append({
                        "title": title,
                        "link": link,
                        "published": entry.get("published", ""),
                        "summary": summary_clean,
                        "feed_source": url
                    })
        except Exception as e:
            st.error(f"Error fetching feed {url}: {e}")
            
    # Deduplicate internally within this batch
    unique_links = set()
    deduped_articles = []
    for article in all_articles:
        if article["link"] not in unique_links:
            unique_links.add(article["link"])
            deduped_articles.append(article)
            
    if progress_callback:
        progress_callback(1.0, "Data collection complete!")
        
    return deduped_articles

def synthesize_batch(api_key, batch_index, batch_data, persona, report_format, use_memory=True, past_report=""):
    """
    Data Serialization and Direct Communication with Claude AI.
    """
    today_str = date.today().strftime("%B %d, %Y")
    
    # 1. Serialization of raw data (Only NEW articles)
    raw_content = ""
    for idx, art in enumerate(batch_data):
        raw_content += f"[{idx+1}] TITLE: {art['title']}\n"
        raw_content += f"URL: {art['link']}\n"
        raw_content += f"SUMMARY: {art['summary'][:1500]}...\n"
        raw_content += "-" * 40 + "\n"
        
    # 2. Process Memory Context
    memory_block = ""
    if use_memory and past_report:
        memory_block = (
            "CONTEXT FROM PREVIOUS INTELLIGENCE REPORT:\n"
            f"{past_report}\n\n"
            "INSTRUCTION FOR IMPACT ANALYSIS: You must evaluate how the NEW articles below relate to, reinforce, or break the trends mentioned in the PREVIOUS report above.\n\n"
            "---\n\n"
        )
        
    # 3. Final Prompt Structure (User Prompt + Input Data)
    prompt_content = f"{memory_block}Today is {today_str}. Here are the totally NEW, unseen articles:\n\n{raw_content}\n\n{report_format}"

    # --- API CONNECTION ---
    if not api_key:
        time.sleep(2) # Simulate Anthropic delay
        
        mock_output_md = f"""## Market trends
* (Mock) The industrial automation sector continues to rise with new AMR deployments. (Source: The Robot Report)
* Factories in Europe and China are doubling their budget for flexible robotic arms. (Source: Asian Tech)

## Competitor & industry moves
* (Mock Data) Universal Robots announced a new generation of cobots with 4D micro-force sensors. (Source: Robotics Tomorrow)
* KUKA strengthens European supply chains by acquiring X-Sensors. (Source: IE3)

## Funding & M&A
* 🇺🇸 Softbank poured $500M USD into Boston Dynamics' domestic Humanoid project. (Source: TechCrunch)

## Southeast Asia & Vietnam spotlight
* 🇻🇳 Vinamilk and Samsung Bắc Ninh open a mega Logistics plant utilizing robotic arms. (Source: VNExpress)
* 🇸🇬 The Singaporean Government established a 100M SGD fund for Deep-Tech Automation startups. (Source: E27)

## Impact Analysis: New developments vs Previous report
* The new investment in Boston Dynamics directly reinforces the humanoid scaling trend reported previously, fast-tracking commercial deployment.
* Universal Robots' new 4D sensor cobot might challenge the existing market dominance mentioned in our last report.

## Strategic implications for VinDynamic
* **Opportunity 1:** Electronics giants (Samsung) in VN are desperate for automated chip-handling solutions. VinDynamic should propose a Pilot package integrating soft grippers to secure a 100K$ contract. (Source: Context linking to VNExpress)
* **Threat:** Manufacturers from Guangdong (CN) are entering the SEA market, slashing AGV prices by 15%. (Source: General trend)
* **Action:** Shift positioning. Reduce hardware competition, focus heavily on AI Controllers (Navigational Intelligence). (Source: Strategic assumption)

## Top 3 articles to read in full
1. [Robotics News 1]({batch_data[0]['link']}) - {batch_data[0]['title']}

***Headline of the day***: A pivotal day for the market as multi-million dollar investments pour heavily into the Humanoid ecosystem, opening a bright door for VinDynamic to exploit the soft-gripper logistics chain.
"""
        return {
            "batch_index": batch_index,
            "articles_processed": len(batch_data),
            "report_content": mock_output_md
        }
    else:
        # REAL API CALL TO ANTHROPIC SDK
        try:
            client = anthropic.Anthropic(api_key=api_key)
            message = client.messages.create(
                model=st.session_state.get("selected_model", "claude-sonnet-4-6"),
                max_tokens=3000,
                system=persona,
                messages=[{"role": "user", "content": prompt_content}]
            )
            return {
                "batch_index": batch_index,
                "articles_processed": len(batch_data),
                "report_content": message.content[0].text
            }
        except Exception as e:
            return {
                "batch_index": batch_index,
                "articles_processed": len(batch_data),
                "report_content": f"🚨 **SYSTEM ERROR CALLING CLAUDE API:** {str(e)}\n\nPlease double-check your API Key and billing status."
            }

# --- UI BUILDING ---

def main():
    colTitle, colSettings = st.columns([8, 2])
    
    with colTitle:
        st.title("🤖 VinDynamic Intelligence Agent")
        st.markdown("Specialized AI Architecture for Market Intelligence. 🧠 Featuring **Tokens Optimization (Delta Tracking)** & **Context Memory**.")
        
    with colSettings:
        st.write("") 
        st.write("") 
        with st.popover("⚙️ Settings (Keys)", use_container_width=True):
            st.markdown("**Platform Credentials**")
            default_key = config.ANTHROPIC_API_KEY if config.ANTHROPIC_API_KEY else ""
            api_key = st.text_input("🔑 Anthropic API Key", type="password", help="Được bảo mật cục bộ ở file .env dưới máy.", value=default_key)
            if st.button("💾 Lưu vĩnh viễn Key (lần sau tự nhận)", use_container_width=True):
                if api_key:
                    from dotenv import set_key
                    if not os.path.exists(".env"):
                        open(".env", "w").close()
                    set_key(".env", "ANTHROPIC_API_KEY", api_key)
                    config.ANTHROPIC_API_KEY = api_key
                    st.success("✅ Đã đóng băng Key vào ổ cứng an toàn 100%!")
                else:
                    st.warning("Xin hãy dán API Key trước khi bấm Lưu.")
            
            st.divider()
            st.markdown("**Core Parameters**")
            available_models = [
                "claude-sonnet-4-6", 
                "claude-opus-4-6", 
                "claude-sonnet-4-5-20250929", 
                "claude-haiku-4-5-20251001"
            ]
            selected_model = st.selectbox("🧠 AI Model", available_models, key="selected_model")
            max_articles = st.number_input("Max Articles to Process", min_value=10, max_value=500, value=50, step=10, help="Giới hạn số lượng bài để tiết kiệm Token", key="max_articles_limit")

    # 1. SIDEBAR: Configuration inputs
    with st.sidebar:
        st.header("⚙️ Agent Configuration")
        
        if not api_key:
            st.info("💡 Running in MOCK mode. Add your Anthropic API Key in the top-right Settings to enable Claude.")

        st.subheader("🧠 Memory Hooks")
        use_memory = st.toggle("Inject Previous Report Context?", value=True)
        if use_memory:
            st.caption("🔍 Claude will cross-reference the PREVIOUS report to detect escalating trends or perform Impact Analysis.")

        st.subheader("📰 RSS Sources (Daily Scan)")
        default_rss = "\n".join(config.RSS_FEEDS)
        rss_input = st.text_area("Source List (1 URL per line)", value=default_rss, height=180)
        rss_urls = [url.strip() for url in rss_input.split('\n') if url.strip()]
        
        st.subheader("🎯 Pre-Filtering Keywords")
        default_kw = ", ".join(config.KEYWORDS)
        kw_input = st.text_area("Comma-separated values", value=default_kw, height=100)
        keyword_list = [kw.strip() for kw in kw_input.split(',') if kw.strip()]
        
        st.subheader("🕵️ Persona Injection")
        persona_input = st.text_area("System Directive", value=config.ANALYST_PERSONA, height=200)

        st.subheader("📑 Report Architecture")
        try:
            default_format = config.REPORT_FORMAT
        except:
            default_format = "Placeholder Format. Please refresh."
        format_input = st.text_area("Strict Output Format (Markdown)", value=default_format, height=250)
        
        # Thêm nút Clear History để quét lại từ đầu
        if st.button("🗑️ Xóa bộ nhớ Lịch sử (Quét lại toàn bộ bài)"):
            if os.path.exists(HISTORY_FILE):
                os.remove(HISTORY_FILE)
            st.success("Đã xóa bộ nhớ. Trạng thái pipeline sẽ phân loại mọi nguồn như mới.")

    # 2. MAIN AREA: Execution
    st.divider()
    
    col1, col2 = st.columns([1, 4])
    with col1:
        start_btn = st.button("🚀 Run System Pipeline", type="primary", use_container_width=True)
        
    # --- KHỐI THỰC THI (Chỉ chạy 1 lần khi ấn nút) ---
    if start_btn:
        st.info("Initiating Agent Pipeline...")
        
        progress_bar = st.progress(0.0)
        status_text = st.empty()
        
        def update_progress(ratio, text):
            progress_bar.progress(ratio)
            status_text.text(text)
        
        st.subheader("Tier 1 & 2: Data Pipeline (Fetching NEW Articles)")
        
        with st.spinner("Parsing RSS feeds, matching keywords & Filtering Old Articles..."):
            history_data = load_history()
            previous_links = set(history_data.get("links", []))
            past_report = history_data.get("last_report", "")
            
            # Fetch CHỈ BÀI MỚI (chưa xuất hiện trong previous_links)
            articles_raw = fetch_rss_feeds(rss_urls, keyword_list, progress_callback=update_progress, previous_links=previous_links)
            
            limit = st.session_state.get("max_articles_limit", 50)
            articles = articles_raw[:limit]
            
            # Lưu các thông số hiển thị ra session_state
            st.session_state['total_fetched'] = len(articles_raw)
            st.session_state['articles_passed'] = len(articles)
        
        if len(articles) > 0:
            st.session_state['pipeline_success'] = True
            
            df = pd.DataFrame(articles)[['title', 'feed_source', 'link']]
            st.session_state['pipeline_df'] = df
            
            st.subheader("Tier 3: Core Intelligence (Claude Synthesis)")
            
            with st.status("Aggregating Context & Data -> Requesting comprehensive report from Claude...", expanded=True) as status:
                st.write(f"Serializing {len(articles)} NEW Articles -> Injecting Previous Report Context -> Dispatching Payload...")
                
                result = synthesize_batch(
                    api_key=api_key, 
                    batch_index=1, 
                    batch_data=articles, 
                    persona=persona_input, 
                    report_format=format_input, 
                    use_memory=use_memory, 
                    past_report=past_report
                )
                status.update(label="Claude completed the Delta Intelligence Briefing! ✅", state="complete", expanded=False)
            
            with st.spinner("Đang hóa hơi Markdown để ép mặt chữ dập File PDF..."):
                pdf_bytes = generate_pdf(result['report_content'])
            
            st.session_state['articles_processed'] = result['articles_processed']
            st.session_state['report_content'] = result['report_content']
            st.session_state['pdf_bytes'] = pdf_bytes
            
            # Lưu lịch sử (URL mới + Report mới) để dùng chống trùng lặp cho những lần click Run sắp tới
            new_links = [art['link'] for art in articles]
            save_history(new_links, result['report_content'])
            
        else:
            # Không có bài nào mới
            st.session_state['pipeline_success'] = True
            st.session_state['pipeline_df'] = pd.DataFrame()
            st.session_state['report_content'] = "⚠️ **Không có tin tức nào mới (Delta = 0)** kể từ đợt báo cáo lần trước. Toàn bộ các bài trên RSS đều đã được phân tích. Hãy thử lại vào ngày mai hoặc nới lỏng từ khóa mục tiêu!"
            st.session_state['pdf_bytes'] = None

    # --- KHỐI GIAO DIỆN HIỂN THỊ (Bền vững, không bị ẩn khi Download) ---
    if st.session_state.get('pipeline_success'):
        # 1. Pipeline Logs Info
        st.subheader("Tier 1 & 2: Data Pipeline Results")
        if st.session_state.get('articles_passed', 0) > 0:
             st.success(f"✅ Lọc thành công bài mới (tránh trùng lặp triệt để để Tối Ưu Token)! Thu thập được **{st.session_state['total_fetched']}** tin mới chưa từng xuất hiện. Phân tích top **{st.session_state['articles_passed']}** tin nhắn.")
        else:
             st.info("✅ Pipeline hoạt động: Đã quét nhưng mọi bài báo đều là bài cũ từng phân tích rồi. Cắt luồng lên LLM để bảo toàn Token.")
             
        # 2. DataFrame (Raw Data)
        if st.session_state.get('pipeline_df') is not None and not st.session_state['pipeline_df'].empty:
            st.dataframe(st.session_state['pipeline_df'], use_container_width=True, hide_index=True)
            
        # 3. Report Display
        st.divider()
        st.subheader("📊 Tier 3 & 4: Final Intelligence Briefing (Markdown)")
        if st.session_state.get('articles_processed', 0) > 0:
            st.markdown(f"#### 📂 Báo cáo Delta (Chỉ tính cước token cho đúng {st.session_state['articles_processed']} diễn biến mới!):")
        st.markdown(st.session_state.get('report_content', ''))
        
        # 4. Download Feature
        st.divider()
        st.subheader("📥 Export Intelligence Report")
        
        if st.session_state.get('pdf_bytes'):
            st.download_button(
                label="📄 Download Report as PDF",
                data=st.session_state['pdf_bytes'],
                file_name=f"VinDynamic_Delta_Report_{date.today().strftime('%Y-%m-%d')}.pdf",
                mime="application/pdf",
                type="primary"
            )
            
            if st.button("🔄 Clear Output"):
                st.session_state['pipeline_success'] = False
                st.rerun()
        elif st.session_state.get('pipeline_df') is None or st.session_state['pipeline_df'].empty:
            st.warning("Không có dữ liệu mới để xuất file PDF.")
            if st.button("🔄 Clear Output"):
                st.session_state['pipeline_success'] = False
                st.rerun()
        else:
            st.error("🚨 PDF Generation Failed. The system could not compile the physical file.")

if __name__ == "__main__":
    main()
